CREATE DATABASE LibraryManagement;
USE LIBRARYMANAGEMENT;

CREATE TABLE BOOKS(
BOOK_ID INT PRIMARY KEY,
TITLE VARCHAR(255) NOT NULL,
AUTHOR VARCHAR(100) NOT NULL,
GENRE VARCHAR(50),
PUBLICATION_YEAR INT,
ISBN VARCHAR(13) UNIQUE,
AVAILABLE_COPIES INT DEFAULT 1
);
SELECT * FROM BOOKS;



CREATE TABLE BORROWERS(
BORROWER_ID INT PRIMARY KEY auto_increment,
FIRST_NAME VARCHAR(50) NOT NULL,
LAST_NAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(100) UNIQUE,
PHONE VARCHAR(15),
RegistrationDate timestamp DEFAULT current_timestamp
);

CREATE TABLE LOANS(
LOAN_ID INT PRIMARY KEY auto_increment,
BOOK_ID INT  REFERENCES BOOKS(BOOK_ID),
BORROWER_ID INT REFERENCES BORROWERS(BORROWER_ID),
LOAN_DATE DATE NOT NULL DEFAULT (CURRENT_DATE),
DUE_DATE DATE NOT NULL,
RETURN_DATE DATE NOT NULL
);
